### ISSUE TITLE
citations are not shown 

### ISSUE THREAD

**Issue by rabeehk** [glederrey/EPFL_thesis_template#3]
Hi
I am using the template, thanks for providing it, for me the citations are not found, I am following the template, so I copied the papers I want to cite in tail/bibliography as 

```
 @techreport{white2017inference,
  title={Inference is everything: Recasting semantic resources into a unified evaluation framework},
  author={White, Aaron Steven and Rastogi, Pushpendre and Duh, Kevin and Van Durme, Benjamin},
  booktitle={Proceedings of the Eighth International Joint Conference on Natural Language Processing},
  year={2017}
}
```

then the biobliography is included in the main latex file as done in the template:

```
\include{tail/biblio}
```

the overall template is almost unchanged.  Below please find the figure showing the compilation logs from overleaf:

https://ibb.co/qYb7Wqt

Many thanks

Rabeeh

**Comment by glederrey** [comment]
Without having access to your full code, it's quite difficult to help you. It seems that natbib cannot find the keys you're trying to use to cite the articles. 

I tried on the "empty" template to add a new entry in the file bibliography.bib and to cite it and it worked without issues. 

So, I guess that this issue comes from your files directly and not the template itself.

**Comment by rabeehk** [comment]
Hi
Thanks, I realized I was adding the bibliography in the wrong place. sorry for this.
